let invoice = {
  id: 1,
  customerName: "Mohsin Ali",
  customerPhoneNumber: "03000786936",
  vehicleNumber: "leb-9920",
  timeIn: DateTime,
  timeOut: DateTime,
  employeeName: "Ali, hamza",
  total: 3500,
  createdAt: Date,
  updatedAt: Date,
  invoiceDetail: [
    {
      id: 1,
      deptId: 1,
      productId: 1,
      deptDetailId: 1,
      deptDetailPrice: 400,
      productName: "oil",
      productSalePrice: 1000,
      companyName: "Speedy Oil",
      subTotal: 1400,
      createdAt: Date,
      updatedAt: Date,
    },
    {
      id: 2,
      deptId: 2,
      productId: 1,
      deptDetailId: 1,
      deptDetailPrice: 400,
      productName: "half Assembly",
      salePrice: 1000,
      companyName: "Pakistan Engine",
      subTotal: 500,
      createdAt: Date,
      updatedAt: Date,
    },
    {
      id: 3,
      deptId: 3,
      productId: 1,
      deptDetailId: 1,
      deptDetailPrice: 400,
      productName: "nitrogen",
      salePrice: 600,
      companyName: "Pakistan Oxygen",
      subTotal: 2500,
      createdAt: Date,
      updatedAt: Date,
    },
  ],
};
