let department = {
  id: 1,
  name: [
    "surgical as mechanical",
    "bloodBank as oilChange",
    "physiotherapy as WheelAlignmentBalancing",
    "neuoro as electrician",
    "dermotology as detailingCarWash",
    "orthopedic as dentingPainting",
    "emergency as tire",
    "test3 as laith like kharadia",
    "test4 as acWork like compressor, condesor, pipe",
    "test5 as expense",
    "test2 as electronics like Speakers, buffers",
    "test1 as decoration",
    "pharmacy as autoParts",
  ],
  createdAt: "DateTime",
  updateAt: "DateTime",
};

let departmentDetail = [
  {
    id: 1,
    deptId: 1,
    deptName: "mechanical",
    type: [
      "halfTunning",
      "fullTunning",
      "suspensionWork",
      "headWork",
      "breakService",
      "scanner",
      "transmissionRepairing",
      "transmissionReplacement",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 2,
    deptName: "oilChange",
    type: ["engineOil", "oilFilter", "airFilter", "acFilter", "etc"],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 3,
    deptName: "WheelAlignmentBalancing",
    type: ["wheelAlignment", "balancing", "weights", "etc"],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 4,
    deptName: "electrician",
    type: [
      "scanner",
      "headLights",
      "horn",
      "absWork",
      "sensers",
      "airBag",
      "hybridWork",
      "relay",
      "switches",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 5,
    deptName: "detailingCarWash",
    type: [
      "service",
      "wash",
      "interiorDetailing",
      "outerDetailing",
      "fullDetailing",
      "engineDetailing",
      "compoungPolish",
      "waxing",
      "coding",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 6,
    deptName: "dentingPainting",
    type: [
      "bumperFitting",
      "mudgadeShields",
      "dentingPerPiece",
      "dentingPaintingPerPiece",
      "pentingPerPiece",
      "fullDenting",
      "fullPainting",
      "fullDentingPainting",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 7,
    deptName: "tire",
    type: ["tires", "rims", "nitrogen", "tireChange", "pencture", "etc"],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 8,
    deptName: "laith",
    type: [
      "suspension",
      "shoksRepairing",
      "breakDiskPolish",
      "bushesChange",
      "bairingChange",
      "steeringAssembly",
      "repairing",
      "cvJointReplacement",
      "cvJointRepairing",
      "headRepairing",
      "blockRepairing",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 9,
    deptName: "acWork",
    type: [
      "compressorReplacement",
      "currensor",
      "bairingReplace",
      "pipe",
      "acService",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
  {
    id: 1,
    deptId: 10,
    deptName: "expense",
    type: [
      "breakFast",
      "lunch",
      "dinner",
      "guestFood",
      "chaye",
      "drinks",
      "electricityBill",
      "waterBill",
      "internetBill",
      "etc",
    ],
    createdAt: "DateTime",
    updateAt: "DateTime",
  },
];

let employees = {
  id: 1,
  firstName: "Azhar",
  lastName: "Ali",
  idCard: "42123123-1231-12312",
  localAddress: "johar town",
  permanentAddress: "multan",
  phoneNumber: "03000786936",
  createdAt: "DateTime",
  updatedAt: "DateTime",
  experience: "2 year",
};

let sallery = {
  id: 1,
  emplyId: 1,
  employName: "Ali",
  salleryAmount: 10000,
  workDays: 20,
  perDayAmount: 800,
  casualLeaves: 5,
  createdAt: "DateTime",
  updatedAt: "DateTime",
};

let invoice = {
  id: 1,
  customerName: "Bilal",
  vehicleNumber: "les-12345",
  timeIn: DateTime,
  timeOut: DateTime,
  employeeName: "Ali, hamza",
  total: 5000,
};

let invoicedetail = [
  {
    id: 1,
    invoiceId: 1,
    deptId: 1,
    deptdetailId: 1,
    subTotal: 1000,
  },
  {
    id: 1,
    invoiceId: 1,
    deptId: 2,
    deptdetailId: 1,
    subTotal: 2000,
  },
  {
    id: 1,
    invoiceId: 1,
    deptId: 3,
    deptdetailId: 1,
    subTotal: 2000,
  },
];
